<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' to get to the front page?' => '',
    'Are you sure you want to delete this item?' => '',
    'Biz haqimizda' => 'About Us',
    'Bizning kompaniya' => 'Our Company',
    'Bizning showroomga tashrif buyuring' => 'Visit our showroom',
    'Bizning yangiliklarimizdan doimiy xabardor bo\'lish uchun emailingizni kiriting' => 'Enter your email to stay up to date with our news',
    'Categories' => '',
    'Category' => '',
    'Category ID' => '',
    'Category Icon' => '',
    'Category Products' => '',
    'Chegirma e\'lon qilingan tovarlar' => 'Discounted goods',
    'Chegirmadagi mahsulotlar' => 'Discounted products',
    'Click' => '',
    'Create Category' => '',
    'Create Category Product' => '',
    'Create Product' => '',
    'Create Product Image' => '',
    'Create Slider' => '',
    'Created At' => '',
    'Delete' => '',
    'Description' => '',
    'Email adresingiz' => 'your email',
    'Eng xaridorgir tovarlar' => 'Famous products',
    'Famous' => '',
    'ID' => '',
    'Image Url' => '',
    'Image url' => '',
    'Kategoriyalar' => 'Category',
    'Ko\'proq ko\'rish' => 'See more',
    'Ko\'proq ma\'lumot' => 'More information',
    'Ko\'proq mahsulot' => 'More products',
    'Kontaktlar' => 'Contacts',
    'Kontaktlarimiz' => 'Our contacts',
    'Mahsulot' => 'Product',
    'Mahsulotlar' => 'Products',
    'Manzilimiz' => 'Our Address',
    'Maqolalar' => '',
    'Видеоблог' => 'Videoblog',
    'Публикации' => 'Publications',
    'Name' => '',
    'New' => '',
    'Obuna bo\'lish' => 'Subscribe',
    'Ommabop Mahsulotlar' => 'Famous Products',
    'Orqali ko\'rish' => 'See with',
    'Price' => '',
    'Product Categories' => '',
    'Product ID' => '',
    'Product Images' => '',
    'Products' => '',
    'Reset' => '',
    'Sale' => 'Discount',
    'Sales Procent' => 'Discount Procent',
    'Save' => '',
    'Search' => '',
    'Select ...' => '',
    'Simple' => '',
    'Slider Btn Link' => '',
    'Slider Btn Title' => '',
    'Slider Info' => '',
    'Slider Title' => '',
    'Sliders' => '',
    'So\'m' => 'Soum',
    'Sorry! Page not found.' => '',
    'Status' => '',
    'Tanlangan kategoriya' => 'Selected category',
    'The requested URL was not found on this server. That’s all we know.' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Category Product: {name}' => '',
    'Update Category: {name}' => '',
    'Update Product Image: {name}' => '',
    'Update Product: {name}' => '',
    'Update Slider: {name}' => '',
    'Yangi mahsulotlar' => 'New Products',
    'Yangi qo\'shilgan tovarlar' => 'Newly added products',
    'Yangiliklar' => 'News',
    'Yangiliklarimizdan xabardor bo\'ling' => 'Stay tuned for our news',
    'here' => '',
    'so\'m' => 'soum',
    'Bizni qayerdan topasiz?' => 'Where will you find us?',
    'Call us' => '',
    'Kontakt' => 'Contact',
    'Send an email' => '',
    'Working hours' => '',
    'Katalog' => 'Catalog'
];
